config/routes.rb
Rails.application.routes.draw do
  
  
  resources :recipes, only: [:index,:new,:show,:create,:update,:destroy]
  
  resources :categories, only: [:index,:new,:create]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  resources :users, only: [:edit,:show,:update]
 
  

  
  root :to => 'homes#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # validates :name, presence: true
  has_many :recipes
  attachment :profile_image
        
end
   

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      redirect_to edit_user_path(@user.id)
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:user_name,:user_kana_name,:email,:password,:password_confirmation,:introduction,:profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<table class="table">
		<tr>
				<th><%= image_tag attachment_url(user, :profile_image, :fill, 150, 180, format: "jpg", fallback: "japan.jpg") %></th>
		</tr>
	   <tr>
	  	  <th>名前:
        <%= user.user_name %>
        </th>
    </tr>
    
	<tr>
		<th>人物詳細</th>
  </tr>
  <tr>
	 <th>
	  <div class="scr">
      <%= user.introduction %>
    </div>
		</th>
	</tr>
	<% if current_user == @user %>
	<tr>
		<th>
		<%= link_to "新作レシピ投稿", new_recipe_path, class: "btn btn-info"%>
		</th>
	</tr>
	<tr>
		<th>
		<%= link_to "自分の情報の編集", edit_user_path(user.id), class: "btn btn-info" %>
		</th>
	</tr>
	<% end %>
</table>

app/views/users/edit.html.erb
<div class="flex-item1">
			<%= render "users/sidebar",user: @user %>
</div>
<div class="flex-item2">
<h2>登録情報編集</h2>
<%= form_for(@user) do |f| %>
<table>
  <tbody>
   <tr>
    <td>名前
    <div class="field">
      <%= f.label :" " %>
      <%= f.text_field :user_name, class: "user_name" %>
    </div>
    </td>
   </tr>

   <tr>
    <td>フリガナ
    <div class="field">
      <%= f.label :" " %>
      <%= f.text_field :user_kana_name, class: "user_kana_name" %>
    </div>
    </td>
   </tr>

   <tr>
    <td>詳細
    
     <div class="field">
      <%= f.label :" " %>
      <%= f.text_area :introduction, size: "20x10" %>
     </div>
  
    </td>
   </tr>
   <tr>
    <td>
    <div class="field">
      <%= f.label :"画像" %>
      <%= f.attachment_field :profile_image %>
    </div>
    </td>
   </tr>
  </tbody>
 
</table>
<div class="actions">
	<%= f.submit "編集内容を保存する", class: "btn btn-info" %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
		<div class="flex-item1">
			<%= render "users/sidebar",user: @user %>
    </div>
		<div class="flex-item2">

		<% @recipes.each do |recipe| %>
		<table class="table tables-bordered">
					<tbody>
						<tr>
								<th><%= image_tag attachment_url(recipe.user, :profile_image, :fill, 50, 50, format: "jpg", fallback: "japan.jpg") %><br>
								<%=link_to recipe.user.user_name, user_path(recipe.user.id) %></th>
								<th><br><br><%= link_to recipe.title, recipe, class: "recipe_#{recipe.id}" %></th>
								<th><br><br>カテゴリー:<%=link_to recipe.category.name, categories_path(recipe.category.id) %></th>
								
								<th><br><br>更新日:<%= recipe.updated_at.to_s(:datetime_jp) %></th>
						</tr>
					</tbody>
		</table>			
		<% end %>
	


</div>