config/routes.rb
Rails.application.routes.draw do
  
  
  resources :recipes, only: [:index,:new,:show,:create,:update,:destroy]
  
  resources :categories, only: [:index,:new,:create]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  resources :users, only: [:edit,:show,:update]
 
  

  
  root :to => 'homes#top'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Wsk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="http://code.jquery.com/jquery-3.1.0.min.js"></script>

    <script>
      $(function(){
        // #で始まるリンクをクリックしたら実行されます
        $('a[href^="#"]').click(function() {
          // スクロールの速度
          var speed = 400; // ミリ秒で記述
          var href= $(this).attr("href");
          var target = $(href == "#" || href == "" ? 'html' : href);
          var position = target.offset().top;
          $('body,html').animate({scrollTop:position}, speed, 'swing');
          return false;
        });
      });
    </script>

    <style>
    .flexbox {
    display: flex; /* 要素をflexコンテナとして定義する */
    width: 100%; /* flexコンテナの横幅を指定する */
    height: 100%; /* flexコンテナの高さを指定する */
    
    flex-direction: row;
    }
    .flex-item1 {
    flex-basis: 20%; /* flexアイテムの幅を割合で指定 */
    

    }
    .flex-item2 {
    flex-basis: 70%; /* flexアイテムの幅を割合で指定 */
    margin: auto;

    }

    .flex-item3 {
    width: 100% !important;
    height: 80px !important;
    padding: 30 !important;
    margin-left: auto;
    font-size: 30pt;
    }

    .flex-itemX {
    width: 100% !important;
    height: 80px !important;
    margin-top: 20%;
    }
   
   .flex-itemY {
    width: 100% !important;
    height: 80px !important;
    margin-top: 80px;
    }
    </style>
    
  
  </head>

<body>
<% if request.path != "/homes/top"%>

  <header>

  <div class="container m-5">
    <div class="row">
      <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand " href="#">Plus Delicieux</a>
          <ul class="navbar-nav">

          <% if current_user && current_user == @user %>
            <li class="nav-item active">
              <%= link_to "マイページ", user_path(current_user.id), class: "nav-link" %></li>
            
          <%end%>
          <li class="nav-item active">
              <%= link_to "logout", destroy_user_session_path, class: "nav-link", method: :delete %></li>
            <li class="nav-item active">
              <%= link_to "レシピ一覧", recipes_path, class: "nav-link" %></li>
            <li class="nav-item active">
              <%= link_to "ジャンル一覧", categories_path, class: "nav-link" %></li>
            
          </ul>
     </nav>
    </div>
  </div>
  </header>
  <% end %>
  
  <div class="flexbox">

  <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
  <% end %>

    <%= yield %>
  </div>
  </body>
</html>